### ISSUE TITLE
Cpu usage suddenly went up to 99%

### ISSUE THREAD

**Issue by Lectem** [rinigus/collectd#7]
*   Version of collectd: 5.6.0
*   Operating system / distribution: sailfish os 2.2.0

## Expected behavior

taking less than 1% cpu

## Actual behavior

I am not sure what happened exactly, but the battery suddenly became hot and when checking top, collectd was using all the cpu.

## Steps to reproduce

I dont have any specific repro, I was just using a web browser

It was installed by SystemDataScope through OpenRepo. If there is any way I could get more info (config, callstack ...?) please tell me how to get those.

**Comment by rinigus** [comment]
You could check if there is something in journal by running 

```
devel-su journalctl -f
```

Sounds strange. I, personally, don't have 2.2.0 on my device and cannot check whether it is caused by the upgrade. For me it will take a while before I can hit that version - would have to update port on the device first.

After checking journal: does this behavior persist after reboot? Or restart of collectd via systemdatascope?

**Comment by Lectem** [comment]
I couldn't reproduce the issue, but I ended up uninstalling it as SystemDataScope was not working very well, perhaps some issue on my setup.
closing the issue !
